name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

env:
  # https://github.com/actions/virtual-environments/tree/main/images/macos
  DEVELOPER_DIR: /Applications/Xcode_12.4.app/Contents/Developer
  MACOS_SDK: macosx11.1

  PROJECT: AboutThisApp.xcodeproj
  SCHEME: AboutThisApp

  EXAMPLE_PROJECT: Example/ExampleApp.xcodeproj
  EXAMPLE_SCHEME: ExampleApp

jobs:
  job-main:
    name: Build and Test
    runs-on: macOS-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v2

      - name: xcode version
        run: xcodebuild -version -sdk

      - name: unit tests
        run: |
          set -o pipefail
          xcodebuild clean test \
              -project "$PROJECT" \
              -scheme "$SCHEME" \
              -sdk "$MACOS_SDK" \
              -destination "arch=x86_64" \
              ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO | xcpretty -c

      - name: ui tests
        run: |
          set -o pipefail
          xcodebuild clean test \
              -project "$EXAMPLE_PROJECT" \
              -scheme "$EXAMPLE_SCHEME" \
              -sdk "$MACOS_SDK" \
              -destination "arch=x86_64" \
              ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO | xcpretty -c
